spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bytesprint?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

logging:
  level:
    com:
      sac:
        demo:
          mapper : debug